### ISSUE TITLE
Prefix Management

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/portal#102]
Test and add OpenAPI docs to the `views.py` file for each of the Prefix Management API endpoints:
- [ ] `api/prefixes/create` Issue #101 
- [ ] `api/prefixes/delete` Issue #102
- [ ] `api/prefixes/permissions/set` Issue #103
- [ ] `api/prefixes/token` Issue #104
- [ ] `api/prefixes/update` Issue #105
